# Generated by Django 5.2.14 on 2026-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_wastecollection_alter_college_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('power_usage', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_smart_device',
            },
        ),
    ]
